server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb://localhost/fklast
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fklast?serverTimezone=UTC
      username: "root"
      password: "root"
  profiles:
    active: dev
  mail:
    username: 215368433@qq.com
    password: pcaekwvaisxvcbcg
    default-encoding: UTF-8
    host: smtp.qq.com
  servlet:
    multipart:
      #      单个文件大小
      max-file-size: 1500MB
      #      总上传文件大小
      max-request-size: 3000MB
      #      文件达到多少时进行磁盘写入
      file-size-threshold: 4000MB
      enabled: false
  redis:
    host: localhost
    port: 6379
#    password: "1236987415q"
  cache:
    type: redis
    redis:
      time-to-live: 5m
      #      是否开启前缀
      use-key-prefix: true
      key-prefix: sms_

mybatis-plus:
  global-config:
    db-config:
      table-prefix: fk_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

#公私钥配置
rsa:
  key:
    pubKeyFile: E:\\fuckingkeys\\id_key_rsa.pub
    priKeyFile: E:\\fuckingkeys\\id_key_rsa



fromMail:
  sender: 215368433@qq.com
logging:
  level:
    root: warn
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
